Allow developers to take additional fees from a swap
orca-so/whirlpools pull request #46
Opened 2022-09-14 05:36 UTC by odcheung

- Add a new `swapWithDevFees` function in the `Whirlpool` client class
- Add new `swapQuoteByInputTokenWithDevFees` quote function

Allow developers to take a percentage of a swap prior to executing the swap instruction.

### Note
- Not a smart-contract integration
- Pending testing

2022-09-16 15:10 UTC, matt-allan approved these changes
I'm not familiar enough with the business logic to review that but code wise this looks good to me :+1:

2022-09-18 12:11 UTC, yugure-orca requested changes
Added comments on when input is SOL, data types, etc.

2022-09-20 06:34 UTC, odcheung commented on sdk/src/impl/whirlpool-impl.ts
> +        SwapErrorCode.InvalidDevFeePercentage
i actually ended up removing this check as the calculation here is incorrect and it feels a bit unnecesary (devs should be free to do whatever they want?). The rule is devFee cannot be more than 100% of the original swap amount. Here it's checking the devFee against the post-fee swap amount.

2022-09-20 09:25 UTC, yugure-orca approved these changes

2022-09-20 17:26 UTC, yugure-orca approved these changes

2022-09-20 18:03 UTC, merged