Expose more data on PositionUtil for easier quote generation
orca-so/whirlpools pull request #63
Opened 2022-11-25 11:22 UTC by odcheung

- Add WhirlpoolData, TickArrayData to Position (client object) to allow for an easier time to generate quotes
- Change collect fee to user PositionData instead of client Position since it doesn't need that much info
- Add new TickUtil.getOffsetIndex to calculate array offset index for a position's tick

### Testing
- The `client.getPositions` is used by Orca UI
- Confirmed that it successfully fetches all positions and have identical data to live (test case had 7 positions, SOL & nonSOL pairs)
- The UX performance is actually faster because the old version does not do batch RPC

https://app.asana.com/0/0/1203431351729803/f

2022-11-25 15:47 UTC, yugure-orca requested changes

2022-12-05 03:20 UTC, odcheung commented on sdk/src/impl/whirlpool-client-impl.ts
> +          const position = await this.getPosition(pos, false);
ah nice. good catch.

2022-12-05 03:49 UTC, odcheung commented
@yugure-orca addressed your comments!

2022-12-05 13:57 UTC, odcheung commented on sdk/src/impl/whirlpool-client-impl.ts
> +      .flatMap((x) => (!!x ? x : []));
if you use filter, typescript wouldn't be able to remove the 'null' part from the 'PublicKey | null' type. Here we are telling typescript that we are either returning something or nothing at all, rendering the type back to PublicKey.

2022-12-05 17:09 UTC, yugure-orca approved these changes
LGTM!

2022-12-06 00:37 UTC, merged